env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "next" }]
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-namespace": off
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  import/extensions: off
  import/no-unresolved: off
  class-methods-use-this: off
  consistent-return: off
  no-use-before-define: off
  func-names: off
  no-console: off
  no-param-reassign: off
  no-underscore-dangle: off
  no-shadow: off
  no-restricted-syntax: off
  no-await-in-loop: off
