env:
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  import/extensions: off
  import/no-unresolved: off
  no-console: off
  consistent-return: off